BUILDDIR ?= build
OBJDIR ?= obj

ATARI_DEBUG ?= 0
ATARI_SHOW_FPS ?= 0
ATARI_TARGET_FPS ?= 9

ATARI_NOIR ?= 0
ATARI_NOIR_DITHERING ?= 0

ATARI_CC ?= m68k-atari-mint-gcc
ATARI_SHAREWARE ?= 1
ATARI_SUPERROTT ?= 0
ATARI_SITELICENSE ?= 0
ATARI_ENABLE_FASTMODE ?= 1
ATARI_ENABLE_KBDINT ?= 1
ATARI_ENABLE_BLITTER ?= 1
ATARI_FADE_SCALE ?= 4
ATARI_C2P_VIEW_ZOOM ?= 1
ATARI_C2P_STRICT_NO_OVERLAP ?= 1
ATARI_C2P_FAST_COPY ?= 1
ATARI_C2P_DIRTY_TILES ?= 1
ATARI_C2P_DIRTY_TILE_THRESHOLD ?= 200
ATARI_MAX_CATCHUP_STEPS ?= 0
ATARI_CATCHUP_POLL_INTERVAL ?= 4
ATARI_RENDER_DIVISOR ?= 3
ATARI_ACTOR_THROTTLE_DIV ?= 3
ATARI_MENU_CURSOR_DELAY_TICS ?= 0
ATARI_MENU_EVENT_DRIVEN ?= 1

ATARI_SKIP_PRECACHE ?= 1
ATARI_SKIP_FADES ?= 1
ATARI_SKIP_LIGHTLEVEL ?= 1
ATARI_SKIP_FIZZLE ?= 1

ATARI_CFLAGS ?= -O2 -fomit-frame-pointer -s -std=gnu99 -m68000 \
	-fno-strict-aliasing -DPLATFORM_ATARI=1 -DPLATFORM_TIMER_HZ=200 \
	-DSHAREWARE=$(ATARI_SHAREWARE) -DATARI_ENABLE_FASTMODE=$(ATARI_ENABLE_FASTMODE) \
	-DSUPERROTT=$(ATARI_SUPERROTT) -DSITELICENSE=$(ATARI_SITELICENSE) \
	-DATARI_ENABLE_KBDINT=$(ATARI_ENABLE_KBDINT) \
	-DATARI_ENABLE_BLITTER=$(ATARI_ENABLE_BLITTER) \
	-DATARI_SKIP_PRECACHE=$(ATARI_SKIP_PRECACHE) -DATARI_SKIP_FADES=$(ATARI_SKIP_FADES) \
	-DATARI_FADE_SCALE=$(ATARI_FADE_SCALE) \
	-DATARI_DEBUG=$(ATARI_DEBUG) -DATARI_SHOW_FPS=$(ATARI_SHOW_FPS) \
	-DATARI_TARGET_FPS=$(ATARI_TARGET_FPS) \
	-DATARI_C2P_VIEW_ZOOM=$(ATARI_C2P_VIEW_ZOOM) \
	-DATARI_C2P_STRICT_NO_OVERLAP=$(ATARI_C2P_STRICT_NO_OVERLAP) \
	-DATARI_NOIR=$(ATARI_NOIR) \
	-DATARI_NOIR_DITHERING=$(ATARI_NOIR_DITHERING) \
	-DATARI_C2P_FAST_COPY=$(ATARI_C2P_FAST_COPY) \
	-DATARI_C2P_DIRTY_TILES=$(ATARI_C2P_DIRTY_TILES) \
	-DATARI_C2P_DIRTY_TILE_THRESHOLD=$(ATARI_C2P_DIRTY_TILE_THRESHOLD) \
	-DATARI_MAX_CATCHUP_STEPS=$(ATARI_MAX_CATCHUP_STEPS) \
	-DATARI_CATCHUP_POLL_INTERVAL=$(ATARI_CATCHUP_POLL_INTERVAL) \
	-DATARI_RENDER_DIVISOR=$(ATARI_RENDER_DIVISOR) \
	-DATARI_ACTOR_THROTTLE_DIV=$(ATARI_ACTOR_THROTTLE_DIV) \
	-DATARI_MENU_CURSOR_DELAY_TICS=$(ATARI_MENU_CURSOR_DELAY_TICS) \
	-DATARI_MENU_EVENT_DRIVEN=$(ATARI_MENU_EVENT_DRIVEN) \
	-DATARI_SKIP_LIGHTLEVEL=$(ATARI_SKIP_LIGHTLEVEL) -DATARI_SKIP_FIZZLE=$(ATARI_SKIP_FIZZLE)
ATARI_LDFLAGS ?= -s -nostdlib -L/freemint/libcmini/lib /freemint/libcmini/lib/crt0.o -m68000
ATARI_LIBS ?= -lcmini -lgcc
ATARI_INCLUDES ?= -Irott -Irott/audiolib -I/freemint/libcmini/include
ATARI_AUDIOLIB_SOURCES := \
	rott/audiolib/atari_stubs.c \
	rott/audiolib/atari_music.c \
	rott/audiolib/atari_music_api.c \
	rott/audiolib/debugio.c \
	rott/audiolib/dsl.c \
	rott/audiolib/fx_man.c \
	rott/audiolib/ll_man.c \
	rott/audiolib/multivoc.c \
	rott/audiolib/mv_mix.c \
	rott/audiolib/mvreverb.c \
	rott/audiolib/nodpmi.c \
	rott/audiolib/pitch.c \
	rott/audiolib/user.c \
	rott/audiolib/usrhooks.c
ATARI_SOURCES := $(filter-out rott/amiga_%.c rott/dosutil.c rott/dukemusc.c rott/fx_man.c rott/lookups.c rott/vocdecode.c,$(wildcard rott/*.c)) $(ATARI_AUDIOLIB_SOURCES)
ATARI_OBJECTS := $(addprefix $(OBJDIR)/,$(ATARI_SOURCES:.c=.o))
ATARI_OUTPUT_SHAREWARE ?= $(BUILDDIR)/ROTT.TOS
ATARI_OUTPUT_DARKWAR ?= $(BUILDDIR)/ROTT_DW.TOS
ATARI_OUTPUT_ROTTCD ?= $(BUILDDIR)/ROTT_CD.TOS
ATARI_OUTPUT_ROTTSITE ?= $(BUILDDIR)/ROTT_ST.TOS
ATARI_OUTPUTS := $(ATARI_OUTPUT_SHAREWARE) $(ATARI_OUTPUT_DARKWAR) $(ATARI_OUTPUT_ROTTCD) $(ATARI_OUTPUT_ROTTSITE)
ATARI_FLAGS_STAMP := $(OBJDIR)/.atari_flags

all: rott-huntbgin
.PHONY: FORCE rott-huntbgin rott-darkwar rott-rottcd rott-rottsite
.SECONDARY: $(ATARI_OBJECTS)
FORCE:

# Shareware build (default)
rott-huntbgin: ATARI_SHAREWARE = 1
rott-huntbgin: ATARI_SUPERROTT = 0
rott-huntbgin: ATARI_SITELICENSE = 0
rott-huntbgin: $(ATARI_OUTPUT_SHAREWARE)

# Commercial build
rott-darkwar: ATARI_SHAREWARE = 0
rott-darkwar: ATARI_SUPERROTT = 0
rott-darkwar: ATARI_SITELICENSE = 0
rott-darkwar: $(ATARI_OUTPUT_DARKWAR)

# CD build
rott-rottcd: ATARI_SHAREWARE = 0
rott-rottcd: ATARI_SUPERROTT = 0
rott-rottcd: ATARI_SITELICENSE = 0
rott-rottcd: $(ATARI_OUTPUT_ROTTCD)

# Site license build
rott-rottsite: ATARI_SHAREWARE = 0
rott-rottsite: ATARI_SUPERROTT = 0
rott-rottsite: ATARI_SITELICENSE = 0
rott-rottsite: $(ATARI_OUTPUT_ROTTSITE)

clean:
	$(RM) -r $(ATARI_OUTPUTS) $(OBJDIR)

$(BUILDDIR)/%.TOS: $(ATARI_OBJECTS) | $(BUILDDIR)
	$(ATARI_CC) $(ATARI_LDFLAGS) $(ATARI_OBJECTS) $(ATARI_LIBS) -o $@

$(BUILDDIR):
	mkdir -p $(BUILDDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(ATARI_FLAGS_STAMP): FORCE | $(OBJDIR)
	@tmp="$@.tmp"; \
	{ \
		echo "ATARI_CC=$(ATARI_CC)"; \
		echo "ATARI_CFLAGS=$(ATARI_CFLAGS)"; \
		echo "ATARI_INCLUDES=$(ATARI_INCLUDES)"; \
	} > "$$tmp"; \
	if [ -f "$@" ] && cmp -s "$$tmp" "$@"; then \
		rm -f "$$tmp"; \
	else \
		mv "$$tmp" "$@"; \
	fi

$(OBJDIR)/%.o: %.c $(ATARI_FLAGS_STAMP)
	mkdir -p $(dir $@)
	$(ATARI_CC) $(ATARI_CFLAGS) $(ATARI_INCLUDES) -c $< -o $@
